### ISSUE TITLE
If the app is in the background I can always reopen it

### ISSUE THREAD

**Issue by AndyQus** [qubic/wallet-app#9] opened 2024-05-20 08:41 UTC
If the app is in the background I can always reopen it. But if I push the app out or close it correctly and then restart it, it immediately closes again and cannot be opened.

**Comment by AndyQus** [comment] 2024-05-21 08:25
This error no longer occurs on the iPhone6s with 0.9.1(2). Please

**Comment by sallymoc** [comment] 2024-06-07 06:23
This error only occurs when running the app in Debug mode (the app was installed running xcode and having the device connected). It's not possible to get crash logs from this and I couldn't find a way yet to get logs for this.
When the app is downloaded from Testflight, it runs in Release mode and the issue is not reproducible.

**Comment by Qubic-Hub** [comment] 2024-06-14 12:18
Shall we close this one @sallymoc  ?

**Comment by sallymoc** [comment] 2024-06-19 08:53
I was investigating more on this and seems to be a 'feature' in flutter (https://stackoverflow.com/questions/76587036/flutter-ios-app-crashes-on-device-when-unplugged).
They are 3 different modes: debug, profile and release. See https://docs.flutter.dev/testing/build-modes
With debug mode, it crashes. With profile I've tried and does not. With release we already saw it's also not because it's how we run it from Testflight.
Based on this results, I'll close this.

**Closed by sallymoc** 2024-06-19 08:53 UTC
Labels: bug
